### ISSUE TITLE
Provide portlet functionality

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/project-manager#31]
We could introduce a branch 'portlet, where the file structure is in such a way, that we can easily build a portlet. This branch should be connected the the Jenkins Virtual Machine, so we can trigger auto-deployment of this portlet on portal-testing.

**Comment by julianspaeth** [comment]
Now the project manager should have the portlet functionality and all necessary files. However, the portlet somehow does not deploy on testing, but there is also no error in the log. I will check next week if maybe something went wrong with the war export, which is a bit different to the war export i was used to in eclipse.

**Comment by julianspaeth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Provide portlet functionality (project-manager)](https://trello.com/c/xCDxnIXt/8-provide-portlet-functionality-project-manager)

**Comment by julianspaeth** [comment]
The portlet functionality is provided now and the portlet itself is working.

However there occured an issue because the credentials for the sql database could not been loaded. This was because they were just given as environment variables. I now added them to the properties file (locally), now it worked. Is this a good solution to store them or should they be stored in another way? @sven1103

**Comment by julianspaeth** [comment]
`[ERROR] License for Vaadin Charts 3 not found. Go to vaadin.com/pro for more details.`

appeared on autodeployment.
